### ISSUE TITLE
the result of grep 'MULE-MuDR' is empty

### ISSUE THREAD

**Issue by MuyuenLP** [Immortal2333/Telemeres_and_Centromeres#4]
Dear Immortal2333,
I runned EDTA and get `genome.mod.EDTA.TEanno.gff3`.And then I use `grep` to  extract keywords.I got results of `Copia, Gypsy, Helitron` correctly but when I use `grep 'MULE-MuDR' genome.mod.EDTA.TEanno.gff3 > TE_MULE-MuDR.split.gff3`,I got an empty file.And there is also nothing about MULE-MuDR in `genome.mod.EDTA.TEanno.gff3`.
![2311687008539_ pic](https://github.com/Immortal2333/Telomeres_and_Centromeres/assets/126345154/6c815ae2-3559-4651-b1ce-34bbdf6cd726)
This is the sum of TE annoation.It's the same as this plot in your paper.
![image](https://github.com/Immortal2333/Telomeres_and_Centromeres/assets/126345154/66c539ea-7e81-426f-827e-a8b63fe8dd57)
So which part is the `MULE-MuDR`? What am I doing wrong? Hope to get your help.(By the way,may i know how you drew this line chart?)
Best wishes

**Comment by Immortal2333** [comment]
We actually used the improved TE Annotation (66.47%) instead of EDTA to extract different types of TEs, because EDTA only annotated around 46% in the *Vitis* genus. Perhaps you can consider using this [Pan-genome TE Annotation Pipeline](https://github.com/unavailable-2374/TE_Detective-Annotation) to enhance your results of TE detection. The pipeline I shared serves as an example to demonstrate how we can identify centromeres through TRF, TE, and Gene annotations. Additionally, EDTA can also be used for centromere identification (Copia, Gypsy, and Helitron are acceptable).

![PanTE classified](https://github.com/Immortal2333/Telomeres_and_Centromeres/assets/89448414/5a93ebe0-9885-4b4a-8637-2f78f44d213f)

**Comment by MuyuenLP** [comment]
Dear Immortal2333,
Thanks for your prompt reply,and sorry for not being on github these days
You are so generous in sharing knowledge
Best wishes
